CarService_WebApp/Controllers/AuthController.cs
using CarService_WebApp.Db;
using CarService_WebApp.Models;
using CarService_WebApp.Models.Auth;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CarService_WebApp.Controllers
{
    public class AuthController : Controller
    {
        // GET: Auth
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }

        private readonly UserManager<User, int> userManager;
        private EFDbContext db = new EFDbContext();
        public AuthController() : this(Startup.UserManagerFactory.Invoke()) { }

        public AuthController(UserManager<User, int> userManager)
        {
            this.userManager = userManager;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing & userManager != null)
                userManager.Dispose();
            base.Dispose(disposing);
        }

        public UserManager<User, int> GetUserManager()
        {
            return this.userManager;
        }
        // GET: Auth
        [HttpGet]
        public ActionResult LogIn(string returnUrl)
        {
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                return View("AccessDenied");
            }
            var model = new LogInModel() { ReturnUrl = returnUrl };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> LogIn(LogInModel logInModel, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = await userManager.FindAsync(logInModel.Email, logInModel.Password);

            if (user != null)
            {
                var identity = await userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
                identity.AddClaim(new Claim(ClaimTypes.GivenName, user.Name));
                identity.AddClaim(new Claim(ClaimTypes.Surname, user.Surname));
                identity.AddClaim(new Claim(ClaimTypes.Role, user.Role.Name));
                Request.GetOwinContext().Authentication.SignIn(identity);
                return Redirect(GetRedirectUrl(user.RoleID, returnUrl));
            }

            ModelState.AddModelError("", "Invalid email or password");
            return View();
        }

        public ActionResult LogOut()
        {
            Request.GetOwinContext().Authentication.SignOut(DefaultAuthenticationTypes.ApplicationCookie);
            return RedirectToAction("Index", "Home");
        }

        private string GetRedirectUrl(int userRole, string returnUrl = "")
        {
            string controllerName = db.Roles.FirstOrDefault(r => r.Id.Equals(userRole))?.Name;

            if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
            {
                return returnUrl;
            }

            return Url.Action("Index", controllerName);
        }

        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(ClientRegisterModel registerModel, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = new User {
                UserName = registerModel.Email,
                Name = registerModel.Name,
                Surname = registerModel.Surname,
                Email = registerModel.Email,
                Phone = registerModel.Phone,
                Adress = registerModel.Adress,
                City = registerModel.City,
                RoleID = db.Roles.First(r => r.Name == "Client").Id
            };

            var result = await userManager.CreateAsync(user, registerModel.Password);
            if (result.Succeeded)
            {
                var identity = await userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
                identity.AddClaim(new Claim(ClaimTypes.GivenName, user.Name));
                identity.AddClaim(new Claim(ClaimTypes.Surname, user.Surname));
                identity.AddClaim(new Claim(ClaimTypes.Role, "Client"));
                Request.GetOwinContext().Authentication.SignIn(identity);
                Client client = new Client();
                client.UserID = user.Id;
                db.Clients.Add(client);
                db.SaveChanges();
                return Redirect(GetRedirectUrl(user.RoleID));
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }

            return View();
        }

        [HttpGet]
        public ActionResult ChangePassword(string returnUrl)
        {
            return View(new ChangePasswordModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public async Task<ActionResult> ChangePassword(ChangePasswordModel changePasswordModel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var result = await userManager.ChangePasswordAsync(User.Identity.GetUserId<int>(), changePasswordModel.CurrentPassword, changePasswordModel.NewPassword);
            if (result.Succeeded)
            {
                return Redirect(changePasswordModel.ReturnUrl);
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }

            return View();
        }
    }
}

CarService_WebApp/Controllers/MechanicController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using CarService_WebApp.Db;
using CarService_WebApp.Models;
using CarService_WebApp.Models.Mech;
using Microsoft.AspNet.Identity;
using System.Collections.Generic;
using System.Security.Claims;
using System.Web;

namespace CarService_WebApp.Controllers
{
    [Authorize(Roles = "Mechanic, Admin")]
    public class MechanicController : Controller
    {
        EFDbContext db = new EFDbContext();
        public enum RepairListMode { All, Incoming, Finished, NotFinished };

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RepairsForCurrentWeek(DateTime? startDate)
        {
            int userId = User.Identity.GetUserId<int>();
            int mechanicId = db.Mechanics.FirstOrDefault(m => m.UserID.Equals(userId)).MechanicID;
            DateTime today = startDate.HasValue ? startDate.Value : DateTime.Today;
            DateTime weekFormToday = today.AddDays(7);
            var repairsList = db.Repairs.Where(x => x.MechanicID.Equals(mechanicId) 
                                        && x.StartDate >= today && x.StartDate <= weekFormToday).ToList();
            Dictionary<DateTime, List<Repair>> list = new Dictionary<DateTime, List<Repair>>();
            list[today] = new List<Repair>();
            for (int i = 1; i < 8; i++)
            {
                list[today.AddDays(i).Date] = new List<Repair>();
            }
            foreach (var repair in repairsList)
            {
                if(repair.StartDate.HasValue)
                    list[repair.StartDate.Value.Date].Add(repair);
                    list[repair.StartDate.Value.Date] = list[repair.StartDate.Value.Date].OrderBy(r => r.StartDate).ToList();
            }
            return View(list);
        }

        public ActionResult RepairsForDate(DateTime startDate)
        {
            int userId = User.Identity.GetUserId<int>();
            int mechanicId = db.Mechanics.FirstOrDefault(m => m.UserID.Equals(userId)).MechanicID;
            var repairs = db.Repairs.Where(r => r.MechanicID.Equals(mechanicId)).ToList();
            repairs = repairs.Where(r => r.StartDate.Value.Date == startDate.Date).ToList();
            return View(repairs);
        }

        [HttpGet]
        public ActionResult List()
        {
            int userId = db.Users.FirstOrDefault(u => u.UserName.Equals(User.Identity.Name)).Id;
            int mechanicId = db.Mechanics.FirstOrDefault(m => m.UserID.Equals(userId)).MechanicID;
            var repairsList = db.Repairs.Where(x => x.MechanicID.Equals(mechanicId)).OrderBy(x => x.RequestDate);
            return View(repairsList);
        }

        [HttpPost]
        public ActionResult ListFindPlateNo(string plateNo, string surname, string carMake, RepairListMode mode)
        {
            int userId = db.Users.FirstOrDefault(u => u.UserName.Equals(User.Identity.Name)).Id;
            int mechanicId = db.Mechanics.FirstOrDefault(m => m.UserID.Equals(userId)).MechanicID;
            if (mode == RepairListMode.Incoming)
            {
                var incomingRepairs = db.IncomingRepairs.Where(i => i.MechanicId == null || (i.MechanicId == mechanicId && i.Status == 0)).ToList();
                return View("IncomingRepairListTable", incomingRepairs);
            }
            var repairs = db.Repairs.Where(r => r.MechanicID.Equals(mechanicId)).ToList();
            repairs = FilterWithMode(repairs, mode);
            if(plateNo != "")
            {
                repairs = repairs.Where(r => r.ClientXCar.PlateNo.ToUpper().Equals(plateNo.ToUpper())).ToList();
            }
            if(surname != "")
            {
                repairs = repairs.Where(r => r.Client.User.Surname.ToUpper().Equals(surname.ToUpper())).ToList();
            }
            if(carMake != "")
            {
                repairs = repairs.Where(r => r.ClientXCar.Car.Make.ToUpper().Equals(carMake.ToUpper())).ToList();
            }
            return View("RepairListTable", repairs);
        }

        private List<Repair> FilterWithMode(List<Repair> list, RepairListMode mode)
        {
            switch(mode){
                case RepairListMode.Finished:
                    list = list.Where(r => r.IsFinished).ToList();
                    break;
                case RepairListMode.NotFinished:
                    list = list.Where(r => !r.IsFinished).ToList();
                    break;
                case RepairListMode.Incoming:
                    list = list.Where(r => r.StartDate == null).ToList();
                    break;
            }
            return list;
        }


        [HttpGet]
        public ActionResult CreateRepair(DateTime? startDate)
        {
            if (User.Identity.IsAuthenticated)
            {
                int userId = db.Users.FirstOrDefault(u => u.UserName.Equals(User.Identity.Name)).Id;
                int mechanicId = db.Mechanics.FirstOrDefault(m => m.UserID.Equals(userId)).MechanicID;
                int maxId = 0;
                if (db.Repairs.Count() > 0)
                {
                    maxId = db.Repairs.Max(r => r.RepairID);
                }
                CreateRepairModel createRepairModel = new CreateRepairModel();
                Repair repair = new Repair { RepairID = maxId + 1, MechanicID = mechanicId, RequestDate = DateTime.Now };
                repair.RepairHash = String.Format("{0}-{1}", repair.RequestDate.ToString(@"yyyy\/MM\/dd"), repair.RepairID);
                repair.StartDate = startDate.HasValue ? startDate : DateTime.Now;
                repair.PlannedEndDate = startDate.HasValue ? startDate : DateTime.Now;
                createRepairModel.FormRepair = repair;
                Session["repairPartsList"] = new PartsListModel { PartsList = new List<RepairXPart>() };
                return View(createRepairModel);
            }
            return View("Index");
        }

        [HttpPost]
        public ActionResult AddRepair(CreateRepairModel createRepairModel)
        {
            PartsListModel partsListModel = (PartsListModel)Session["repairPartsList"];
            createRepairModel.FormPartList = partsListModel.PartsList;
            if (!ModelState.IsValid)
                return View("CreateRepair", createRepairModel);

            Client client = db.Clients.Where(c => c.UserID.Equals(createRepairModel.FormUser.Id)).FirstOrDefault();
            if(client == null)
            {
                client = new Client { ClientID = db.Clients.Max(c => c.ClientID) + 1, UserID = createRepairModel.FormUser.Id };
                client = db.Clients.Add(client);
                db.SaveChanges();
            }
            createRepairModel.FormUser = db.Users.Find(createRepairModel.FormUser.Id);

            Car car;
            car = db.Cars
                    .Where(c => c.Make.ToUpper().Equals(createRepairModel.FormCar.Make.ToUpper()) 
                    && c.Model.ToUpper().Equals(createRepairModel.FormCar.Model.ToUpper())
                    && c.Year.Equals(createRepairModel.FormCar.Year)
                    && c.Capacity.Equals(createRepairModel.FormCar.Capacity)
                    && c.Bhp.Equals(createRepairModel.FormCar.Bhp)
                    && c.Version.Equals(createRepairModel.FormCar.Version))
                    .FirstOrDefault();
            if (car == null)
            {
                createRepairModel.FormCar.CarID = db.Cars.Max(c => c.CarID) + 1;
                car = db.Cars.Add(createRepairModel.FormCar);
                db.SaveChanges();
            }

            ClientXCar clientXCar = db.ClientsXCars.Where(cxc => cxc.ClientXCarID.Equals(createRepairModel.FormClientXCar.ClientXCarID))
                                                    .FirstOrDefault();

            if(clientXCar == null)
            {
                int maxId = 0;
                if(db.ClientsXCars.Count() > 0)
                {
                    maxId = db.ClientsXCars.Max(c => c.ClientXCarID);
                }
                clientXCar = new ClientXCar {
                    ClientXCarID = maxId + 1,
                    CarID = car.CarID, ClientID = client.ClientID,
                    PlateNo = createRepairModel.FormClientXCar.PlateNo };
                clientXCar = db.ClientsXCars.Add(clientXCar);
                db.SaveChanges();
            }
            createRepairModel.FormClientXCar = clientXCar;
            createRepairModel.FormRepair.ClientID = client.ClientID;
            createRepairModel.FormRepair.ClientXCarID = clientXCar.ClientXCarID;
            createRepairModel.FormRepair.RequestDate = DateTime.Now;
            createRepairModel.FormRepair = db.Repairs.Add(createRepairModel.FormRepair);

            foreach (var repairXPart in createRepairModel.FormPartList)
            {
                Part part = db.Parts.Where(p => p.Name.ToUpper().Equals(repairXPart.Part.Name.ToUpper())
                                    && p.Price.Equals(repairXPart.Part.Price)).FirstOrDefault();

                if (part == null)
                {
                    int partMaxId = 0;
                    if (db.Parts.Count() > 0)
                        partMaxId = db.Parts.Max(p => p.PartID);
                    part = new Part { PartID = partMaxId + 1, Name = repairXPart.Part.Name, Price = repairXPart.Part.Price };
                    part = db.Parts.Add(part);

                    RepairXPart rXp = new RepairXPart
                    {
                        RepairXPartID = repairXPart.RepairXPartID,
                        RepairID = createRepairModel.FormRepair.RepairID,
                        PartID = part.PartID,
                        Quantity = repairXPart.Quantity,
                        Total = part.Price * repairXPart.Quantity
                    };
                    rXp = db.RepairsXParts.Add(rXp);
                    db.SaveChanges();
                }
                else
                {

CarService_WebApp/Views/Shared/AccessDenied.cshtml
@{
    ViewBag.Title = "AccessDenied";
}

<h2>Access Denied</h2>

CarService_WebApp/Views/Shared/DropdownCarDescList.cshtml
@model List<string>
@{ 
    Layout = null;
}
<ul>
    @foreach(var str in Model)
    {
        <li class="car-dropdown-li">
            @str
        </li>
    }
</ul>

CarService_WebApp/Views/Shared/InvoiceList.cshtml
@model List<CarService_WebApp.Models.Invoice>
@using System.Security.Claims
@{ 
    Layout = null;
    bool isAdmin = ((ClaimsIdentity)User.Identity).Claims.First(c => c.Type == ClaimTypes.Role).Value == "Admin" ? true : false;
    int colspanNo = isAdmin ? 7 : 5;
}
<table class="table">
    <tr>
        <th>Plate number</th>
        @if (isAdmin)
        {
            <th>Car</th>
            <th>Client</th>
        }
        <th>Due date</th>
        <th>Payment date</th>
        <th>Gross amount</th>
        <th></th>
    </tr>
    @foreach(var invoice in Model)
    {
        <tr>
            <td>@invoice.Repair.ClientXCar.PlateNo</td>
            @if (isAdmin)
            {
                <td>@invoice.Repair.ClientXCar.Car.Make&nbsp;@invoice.Repair.ClientXCar.Car.Model</td>
                <td>@invoice.Repair.Client.User.Name&nbsp;@invoice.Repair.Client.User.Surname</td>
            }
            <td>@invoice.DueDate.ToShortDateString()</td>
            <td>@invoice.PaymentDay.ToShortDateString()</td>
            <td>@invoice.GrossAmount zł</td>
            <td id="@invoice.InvoiceID"><span class="glyphicon glyphicon-arrow-down drop-parts" style="cursor: pointer"></span></td>
        </tr>
        <tr>
            <td colspan="@colspanNo">
                <div class="mini-parts-list" style="display: none" id="@invoice.InvoiceID">
                    <table class="table">
                        <tr>
                            <th>Part name</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                        </tr>
                        @foreach (var rxp in invoice.Repair.RepairXParts)
                        {
                            <tr>
                                <td>@rxp.Part.Name</td>
                                <td>@rxp.Part.Price zł</td>
                                <td>@rxp.Quantity</td>
                                <td>@rxp.Total zł</td>
                            </tr>
                        }
                    </table>
                </div>
            </td>
        </tr>
    }
</table>

CarService_WebApp/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@{ 
    string name = "";
    string surname = "";
    string role = "";
    if (User.Identity.IsAuthenticated)
    {
        var identity = (ClaimsIdentity)User.Identity;
        surname = identity.Claims.First(c => c.Type == ClaimTypes.Surname).Value;
        name = identity.Claims.First(c => c.Type == ClaimTypes.GivenName).Value;
        role = identity.Claims.First(c => c.Type == ClaimTypes.Role).Value;
    }
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-3.1.1.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <link href="~/Content/Site.css?" rel="stylesheet" type="text/css" />
    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Car Service BSc", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <ul class="nav navbar-nav navbar-left">
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("My Dashboard", "RedirectToDashboard", "Home", null, new { @class = "navbar-link" })</li>
                    if(role == "Admin")
                    {
                        <li>@Html.ActionLink("Mechanic Dashboard", "Index", "Mechanic", null, new { @class = "navbar-link" })</li>
                    }
                }
            </ul>
            <ul class="nav navbar-nav navbar-right">
                @if (User.Identity.IsAuthenticated)
                {
                    <li>@Html.ActionLink("Signed as, " + name + " " + surname, "ChangePassword", "Auth", new { returnUrl = HttpContext.Current.Request.Url.AbsolutePath }, new { @class = "navbar-link" })</li>
                    <li>@Html.ActionLink("Log out", "LogOut", "Auth", null, new { @class = "navbar-link" })</li>
                }
                else
                {
                    <li>@Html.ActionLink("Register", "Register", "Auth", null, new { @class = "navbar-link" })</li>
                    <li>@Html.ActionLink("Log in", "LogIn", "Auth", null ,new { @class = "navbar-link" })</li>
                }
            </ul>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Car Service Application</p>
        </footer>
    </div>
</body>
</html>